runtime: php74

handlers:
- url: /styles
  static_dir: assets/css
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: assets/images/\1
  upload: images/(.*\.(gif|png|jpg|jpeg|svg))
  
- url: /.*
  script: index.php